
-- ADD vcard COLUMN FOR User TABLE

ALTER TABLE User ADD COLUMN `vcard` TEXT DEFAULT NULL;

-- REMOVE COLUMNS BECOMING DEPRECATED

ALTER TABLE User DROP COLUMN last_name;
ALTER TABLE User DROP COLUMN first_name;
ALTER TABLE User DROP COLUMN telephone;