name: bo-front build

on:
  push:
    branches: [ 'main' ]
    tags: [ 'v*.*', 'v*.*.*' ]
    paths:
      - 'bo-front/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'bo-front/**'

defaults:
  run:
    working-directory: bo-front/

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build
